apiVersion: v1
kind: Secret
metadata:
  name: vfsvsvvds220-secret
  namespace: vfsvsvvds220
type: Opaque
data:
  rootpassword: ${{secret.ROOTPASSWORD}} | base64
  userpassword: ${{secret.USERPASSWORD}} | base64
